name: Let's Encrypt Background Tasks (Cron Jobs)

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 */3 *"

jobs:
  cron_job:
    runs-on: ubuntu-latest
    name: Cron Jobs
    env:
      BITBUCKET_TOKEN: ${{secrets.BITBUCKET_TOKEN}}
      GH_TOKEN: ${{secrets.GH_TOKEN}}
      GITLAB_TOKEN: ${{secrets.GITLAB_TOKEN}}
      EMAIL: ${{secrets.EMAIL}}
    steps:
      - uses: actions/checkout@v2
      - name: Run Cron Jobs
        id: shell_script_run
        run: bash ./letsencrypt/letsencrypt.sh
