name: SoraChat Background Tasks (Cron Jobs)

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  cron_job:
    runs-on: ubuntu-latest
    container:
        image: debian:latest
    name: Cron Jobs
    env:
      GOLANG: 1.19.4
      SORACHAT: 0.10.8
      SORACHAT_WEB: 1.11.18
      SORACHAT_LITE: 0.3.6
      SORACHAT_CALL: 0.3.3
      BITBUCKET_TOKEN: ${{secrets.BITBUCKET_TOKEN}}
      EMAIL: ${{secrets.EMAIL}}
      VITE_DEFAULT_HOMESERVER: "https://sorachat.eu.org"
    steps:
      - uses: actions/checkout@v3
      - name: Run Cron Jobs
        id: shell_script_run
        run: bash ./sorachat/sorachat.sh
      - uses: actions/upload-artifact@v3
        with:
          name: sorachat-v${{ env.SORACHAT }}.tar.gz
          path: sorachat/sorachat-v${{ env.SORACHAT }}.tar.gz
