name: TOR Background Tasks (Cron Jobs)

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  cron_job:
    runs-on: ubuntu-latest
    name: Cron Jobs
    env:
      BITBUCKET_TOKEN: ${{secrets.BITBUCKET_TOKEN}}
      EMAIL: ${{secrets.EMAIL}}
    steps:
      - uses: actions/checkout@v3
      - name: Run Cron Jobs
        id: shell_script_run
        run: bash ./tor/mkp224o.sh
#      - uses: actions/upload-artifact@v3
#        with:
#          name: mkp224o
#          path: tor/mkp224o
